"""
Audio service: constructs URLs for pre-cached audio in Google Cloud Storage.
All audio files are stored in the word_audio/ folder generated by scripts/audio_tts.py.
"""

from config import GCS_BUCKET_NAME

GCS_BASE = f'https://storage.googleapis.com/{GCS_BUCKET_NAME}'


def get_audio_url(word: str) -> str:
    """Get audio URL from GCS."""
    return f'{GCS_BASE}/word_audio/{word.lower()}.mp3'
