"""
Step 2: Upload the reviewed exercise_pool.json to Firestore.

Reads the local JSON file (generated by generate_pool_json.py and reviewed by you),
then uploads each entry to the exercise_pool collection in Firestore.

Usage:
    cd Capstone_Deploy
    python scripts/upload_pool_to_firestore.py

Options:
    --clear   Delete all existing pool documents before uploading (fresh start)
"""

import sys
import os
import json
import hashlib
from dotenv import load_dotenv

load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), '..', 'Backend', '.env'))

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'Backend'))

from google.cloud import firestore
from config import FIRESTORE_DATABASE, POOL_COLLECTION

db = firestore.Client(database=FIRESTORE_DATABASE)

INPUT_FILE = os.path.join(os.path.dirname(__file__), 'exercise_pool.json')


def make_doc_id(phoneme: str, level: int, ipa_key: str, index: int) -> str:
    """Create a stable, unique document ID."""
    key_hash = hashlib.md5(ipa_key.encode()).hexdigest()[:8]
    safe_phoneme = phoneme.replace(':', '_').replace('/', '_')
    return f'{safe_phoneme}_L{level}_{key_hash}_{index}'


def clear_pool():
    """Delete all existing documents in the exercise_pool collection."""
    print('Clearing existing pool...')
    docs = db.collection(POOL_COLLECTION).stream()
    batch = db.batch()
    count = 0
    for doc in docs:
        batch.delete(doc.reference)
        count += 1
        if count % 400 == 0:  # Firestore batch limit is 500
            batch.commit()
            batch = db.batch()
    if count % 400 != 0:
        batch.commit()
    print(f'  Deleted {count} documents')


def upload():
    """Upload exercise_pool.json to Firestore."""
    if not os.path.exists(INPUT_FILE):
        print(f'Error: {INPUT_FILE} not found. Run generate_pool_json.py first.')
        sys.exit(1)

    with open(INPUT_FILE, 'r', encoding='utf-8') as f:
        pool = json.load(f)

    total_docs = 0
    batch = db.batch()
    batch_count = 0

    for phoneme, words in pool.items():
        print(f'Uploading /{phoneme}/ ({len(words)} words)...')

        for ipa_key, data in words.items():
            answer = data['answer']
            sentences = data['sentences']

            for i, sent in enumerate(sentences):
                # Level 1: contextual IPA
                doc_id_l1 = make_doc_id(phoneme, 1, ipa_key, i)
                doc_ref_l1 = db.collection(POOL_COLLECTION).document(doc_id_l1)
                batch.set(doc_ref_l1, {
                    'phoneme': phoneme,
                    'level': 1,
                    'ipa': ipa_key,
                    'answer': answer,
                    'ipa_sentence': sent['ipa_sentence'],
                })
                batch_count += 1
                total_docs += 1

                # Level 2: wrong spelling
                doc_id_l2 = make_doc_id(phoneme, 2, ipa_key, i)
                doc_ref_l2 = db.collection(POOL_COLLECTION).document(doc_id_l2)
                batch.set(doc_ref_l2, {
                    'phoneme': phoneme,
                    'level': 2,
                    'ipa': ipa_key,
                    'answer': answer,
                    'wrong_sentence': sent['wrong_sentence'],
                    'wrong_help_sentence': sent['wrong_help_sentence'],
                })
                batch_count += 1
                total_docs += 1

                # Commit batch if approaching limit
                if batch_count >= 400:
                    batch.commit()
                    batch = db.batch()
                    batch_count = 0

    # Final commit
    if batch_count > 0:
        batch.commit()

    print(f'\n✓ Done! Uploaded {total_docs} documents to Firestore ({POOL_COLLECTION} collection).')


if __name__ == '__main__':
    if '--clear' in sys.argv:
        clear_pool()
        print()

    upload()
